
package com.scc.softdev.services.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IssueImplService", targetNamespace = "http://impl.services.softdev.scc.com/", wsdlLocation = "http://sd01srv.softsystem.pl:8080/SoftDevSrv/services/SoftDev_Issue?wsdl")
public class IssueImplService
    extends Service
{

    private final static URL ISSUEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISSUEIMPLSERVICE_EXCEPTION;
    private final static QName ISSUEIMPLSERVICE_QNAME = new QName("http://impl.services.softdev.scc.com/", "IssueImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sd01srv.softsystem.pl:8080/SoftDevSrv/services/SoftDev_Issue?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISSUEIMPLSERVICE_WSDL_LOCATION = url;
        ISSUEIMPLSERVICE_EXCEPTION = e;
    }

    public IssueImplService() {
        super(__getWsdlLocation(), ISSUEIMPLSERVICE_QNAME);
    }

    public IssueImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISSUEIMPLSERVICE_QNAME, features);
    }

    public IssueImplService(URL wsdlLocation) {
        super(wsdlLocation, ISSUEIMPLSERVICE_QNAME);
    }

    public IssueImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISSUEIMPLSERVICE_QNAME, features);
    }

    public IssueImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IssueImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoftDevIssue
     */
    @WebEndpoint(name = "IssueImplPort")
    public SoftDevIssue getIssueImplPort() {
        return super.getPort(new QName("http://impl.services.softdev.scc.com/", "IssueImplPort"), SoftDevIssue.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoftDevIssue
     */
    @WebEndpoint(name = "IssueImplPort")
    public SoftDevIssue getIssueImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.services.softdev.scc.com/", "IssueImplPort"), SoftDevIssue.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISSUEIMPLSERVICE_EXCEPTION!= null) {
            throw ISSUEIMPLSERVICE_EXCEPTION;
        }
        return ISSUEIMPLSERVICE_WSDL_LOCATION;
    }

}
