
package com.scc.softdev.services.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestCaseImplService", targetNamespace = "http://impl.services.softdev.scc.com/", wsdlLocation = "http://sd01srv.softsystem.pl:8080/SoftDevSrv/services/SoftDev_TestCase?wsdl")
public class TestCaseImplService
    extends Service
{

    private final static URL TESTCASEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTCASEIMPLSERVICE_EXCEPTION;
    private final static QName TESTCASEIMPLSERVICE_QNAME = new QName("http://impl.services.softdev.scc.com/", "TestCaseImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sd01srv.softsystem.pl:8080/SoftDevSrv/services/SoftDev_TestCase?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTCASEIMPLSERVICE_WSDL_LOCATION = url;
        TESTCASEIMPLSERVICE_EXCEPTION = e;
    }

    public TestCaseImplService() {
        super(__getWsdlLocation(), TESTCASEIMPLSERVICE_QNAME);
    }

    public TestCaseImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTCASEIMPLSERVICE_QNAME, features);
    }

    public TestCaseImplService(URL wsdlLocation) {
        super(wsdlLocation, TESTCASEIMPLSERVICE_QNAME);
    }

    public TestCaseImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTCASEIMPLSERVICE_QNAME, features);
    }

    public TestCaseImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestCaseImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoftDevTestCase
     */
    @WebEndpoint(name = "TestCaseImplPort")
    public SoftDevTestCase getTestCaseImplPort() {
        return super.getPort(new QName("http://impl.services.softdev.scc.com/", "TestCaseImplPort"), SoftDevTestCase.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoftDevTestCase
     */
    @WebEndpoint(name = "TestCaseImplPort")
    public SoftDevTestCase getTestCaseImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.services.softdev.scc.com/", "TestCaseImplPort"), SoftDevTestCase.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTCASEIMPLSERVICE_EXCEPTION!= null) {
            throw TESTCASEIMPLSERVICE_EXCEPTION;
        }
        return TESTCASEIMPLSERVICE_WSDL_LOCATION;
    }

}
